services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: unit
      POSTGRES_PASSWORD: unit
      POSTGRES_DB: unit
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unit -d unit"]
      interval: 5s
      timeout: 5s
      retries: 5
 
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data

volumes:
  pgdata:
  dragonflydata:
  kafka_data:
